# Generated by Django 5.0.14 on 2026-06-30 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignment_attachment_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_hostel',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('tuition', models.PositiveIntegerField(default=0)),
                ('hostel_fee', models.PositiveIntegerField(default=0)),
                ('other_charges', models.PositiveIntegerField(default=0)),
                ('other_label', models.CharField(blank=True, max_length=60)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('discount_reason', models.CharField(blank=True, max_length=120)),
                ('discount_by', models.CharField(blank=True, max_length=120)),
                ('scholarship', models.PositiveIntegerField(default=0)),
                ('scholarship_name', models.CharField(blank=True, max_length=120)),
                ('late_fee', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='core.student')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.feechallan'),
        ),
    ]
