# Generated by Django 5.0.14 on 2026-06-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_address_student_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='core.profile')),
            ],
            options={
                'ordering': ['classroom__name', 'classroom__section', 'subject'],
                'unique_together': {('teacher', 'classroom', 'subject')},
            },
        ),
    ]
