# Generated by Django 5.0.14 on 2026-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teachingassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Principal'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('finance', 'Finance'), ('owner', 'Owner / Director')], default='admin', max_length=20),
        ),
    ]
