# Generated by Django 5.0.14 on 2026-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner / Director'), ('principal', 'Principal'), ('admin', 'Administrator (Office)'), ('finance', 'Accountant / Finance'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], default='admin', max_length=20),
        ),
    ]
