# Generated by Django 5.0.14 on 2026-06-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='stage',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Test', 'Test'), ('Offer', 'Offer'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected')], default='Enquiry', max_length=20),
        ),
        migrations.CreateModel(
            name='ConcessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discount', 'Discount'), ('scholarship', 'Scholarship')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('requested_by', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('decided_by', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('decided_on', models.DateTimeField(blank=True, null=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concession_requests', to='core.feechallan')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
