# Generated by Django 5.0.14 on 2026-06-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_staff_active_staff_allowances_staff_basic_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('capacity', models.PositiveIntegerField(default=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=40)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule', to='core.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.exam')),
            ],
            options={
                'ordering': ['date', 'time', 'classroom__name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.student')),
            ],
            options={
                'ordering': ['room__name', 'seat_no'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
