# Generated by Django 5.0.14 on 2026-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_examroom_examschedule_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='final_grade',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='pass_mark',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
