# Generated by Django 5.0.14 on 2026-06-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_school_final_grade_school_pass_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('warden', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Behaviour', 'Behaviour'), ('Bullying', 'Bullying / Fighting'), ('Uniform', 'Uniform / Dress code'), ('Attendance', 'Attendance / Punctuality'), ('Homework', 'Homework / Class work'), ('Property', 'Property damage'), ('Other', 'Other')], default='Behaviour', max_length=20)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Minor', max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.CharField(blank=True, max_length=200)),
                ('reported_by', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='core.student')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.hostelroom'),
        ),
    ]
