# Generated by Django 5.0.14 on 2026-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hostelroom_disciplinerecord_student_hostel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='to_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
