# Generated by Django 5.0.14 on 2026-06-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_smsmessage_error_smsmessage_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(choices=[('Fresh', 'Fresh admission'), ('Transfer', 'Transfer from another school')], default='Fresh', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='b_form',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='board_reg_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_birth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_cnic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='doc_slc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='leaving_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='Pakistani', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_class',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='slc_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='slc_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Left', 'Left'), ('Graduated', 'Graduated'), ('Struck Off', 'Struck off')], default='Active', max_length=12),
        ),
    ]
