# Generated by Django 5.0.14 on 2026-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_student_admission_type_student_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
