# Generated by Django 5.0.14 on 2026-07-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_left_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='arrears',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feechallan',
            name='carried_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feechallan',
            name='transport_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='hostel_fee',
            field=models.PositiveIntegerField(default=8000),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
