# Generated by Django 5.0.14 on 2026-07-01 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feechallan_arrears_feechallan_carried_forward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='guardians', to='core.student'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
