# Generated by Django 5.0.14 on 2026-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_children_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
