# Generated by Django 5.0.14 on 2026-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_applicant_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='late_fee_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
