# Generated by Django 5.0.14 on 2026-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_school_late_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accent_color',
            field=models.CharField(default='#0E7C66', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#15294D', max_length=7),
        ),
    ]
