# Generated by Django 5.0.14 on 2026-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_school_accent_color_school_logo_school_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='default_password',
            field=models.CharField(default='school123', max_length=64),
        ),
    ]
