# Generated by Django 5.0.14 on 2026-07-01 11:24

from django.db import migrations, models


def backfill_session(apps, schema_editor):
    """Tag all existing exams and attendance with the school's current session
    so historical data is grouped under a session instead of blending."""
    School = apps.get_model('core', 'School')
    Exam = apps.get_model('core', 'Exam')
    AttendanceRecord = apps.get_model('core', 'AttendanceRecord')
    school = School.objects.first()
    current = (school.session if school else '') or '2025-26'
    Exam.objects.filter(session='').update(session=current)
    AttendanceRecord.objects.filter(session='').update(session=current)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_session, noop),
    ]
