# Generated by Django 5.0.14 on 2026-07-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_exam_options_attendancerecord_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('frequency', models.CharField(choices=[('monthly', 'Every month'), ('one_time', 'One-time (on admission)'), ('annual', 'Once a year')], default='monthly', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChallanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.feechallan')),
            ],
        ),
    ]
