# Generated by Django 5.0.14 on 2026-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_feehead_challanline'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notify_absent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='notify_feedue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='notify_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_backend',
            field=models.CharField(default='console', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_country_code',
            field=models.CharField(default='+92', max_length=6),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_http_method',
            field=models.CharField(default='GET', max_length=4),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_http_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_twilio_from',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_twilio_sid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_twilio_token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
