# Generated by Django 5.0.14 on 2026-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_school_notify_absent_school_notify_feedue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sms_backend',
            field=models.CharField(choices=[('console', 'Off — log only (test mode)'), ('http', 'HTTP gateway (SMS / WhatsApp provider)'), ('twilio', 'Twilio')], default='console', max_length=10),
        ),
    ]
