# Generated by Django 5.0.14 on 2026-07-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_loginattempt_profile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='online_payments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_bank_account',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_bank_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_bank_iban',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_bank_instructions',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_bank_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_easypaisa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_easypaisa_hash',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_easypaisa_store',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_jazzcash_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_jazzcash_merchant',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_jazzcash_password',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_jazzcash_salt',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('bank', 'Bank transfer'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending verification'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='initiated', max_length=20)),
                ('ref', models.CharField(blank=True, max_length=60)),
                ('gateway_ref', models.CharField(blank=True, max_length=80)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payproof/')),
                ('payer_note', models.CharField(blank=True, max_length=200)),
                ('verified_by', models.CharField(blank=True, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('challan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to='core.feechallan')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online', to='core.feepayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
