# Generated by Django 5.0.14 on 2026-07-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_school_online_payments_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notify_channel',
            field=models.CharField(choices=[('sms', 'SMS only'), ('whatsapp', 'WhatsApp only'), ('both', 'SMS + WhatsApp')], default='sms', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_from',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_provider',
            field=models.CharField(choices=[('twilio', 'Twilio WhatsApp'), ('meta', 'Meta WhatsApp Cloud API')], default='twilio', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
