# Generated by Django 5.0.14 on 2026-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_school_notify_channel_school_whatsapp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
