# Generated by Django 5.0.14 on 2026-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_school_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
