# Generated by Django 5.0.14 on 2026-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_school_subscription_active_school_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_daily_run',
            field=models.DateField(blank=True, null=True),
        ),
    ]
