# Generated by Django 5.0.14 on 2026-07-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_school_last_daily_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='admin_email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='admin_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='school',
            name='admin_username',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
