# Generated by Django 5.0.14 on 2026-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_profile_school_school_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_rate',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
