# Generated by Django 5.0.14 on 2026-07-15 11:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_school_subscription_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('income', 'Subscription Income'), ('expense', 'Platform Expense')], default='income', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_transactions', to='core.school')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
