# Generated by Django 5.0.14 on 2026-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_saastransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/'),
        ),
    ]
