# Generated by Django 5.0.14 on 2026-07-17 11:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_studentleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Praise', 'Praise'), ('Concern', 'Concern'), ('Note', 'General note')], default='Note', max_length=10)),
                ('text', models.CharField(max_length=400)),
                ('teacher_name', models.CharField(blank=True, max_length=80)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes', to='core.profile')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
