# Generated by Django 5.0.14 on 2026-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reversed_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reversed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Voided', 'Voided'), ('Refunded', 'Refunded')], default='Active', max_length=10),
        ),
    ]
