# Generated by Django 5.0.14 on 2026-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_feepayment_reversal_reason_feepayment_reversed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='late_fee_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='late_fee_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='late_fee_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
