# Generated by Django 5.0.14 on 2026-07-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_feechallan_late_fee_locked_school_late_fee_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=80)),
                ('sender_role', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seen_by_family', models.BooleanField(default=False)),
                ('seen_by_staff', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='core.profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.student')),
            ],
            options={
                'ordering': ['created', 'id'],
            },
        ),
    ]
