# Generated by Django 5.0.14 on 2026-07-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by_name', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Fee', 'Fee / Finance'), ('Transport', 'Transport'), ('Facility', 'Facility'), ('Staff', 'Staff conduct'), ('Other', 'Other')], default='Other', max_length=20)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=12)),
                ('response', models.TextField(blank=True)),
                ('handled_by', models.CharField(blank=True, max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.profile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
