# Generated by Django 5.0.14 on 2026-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='admissions/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='admissions/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='previous_school',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='source',
            field=models.CharField(choices=[('Office', 'Office'), ('Online', 'Online')], default='Office', max_length=10),
        ),
    ]
