# Generated by Django 5.0.14 on 2026-07-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_applicant_address_applicant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('locked', models.BooleanField(default=False)),
                ('locked_by', models.CharField(blank=True, max_length=80)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_configs', to='core.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_configs', to='core.exam')),
            ],
            options={
                'unique_together': {('exam', 'classroom', 'subject')},
            },
        ),
    ]
