# Generated by Django 5.0.14 on 2026-07-17 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_gradeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=40)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, 'Outstanding'), (4, 'Exceeds expectations'), (3, 'Meets expectations'), (2, 'Needs improvement'), (1, 'Unsatisfactory')], default=3)),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('reviewer', models.CharField(blank=True, max_length=80)),
                ('created', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='core.staff')),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
    ]
