# Generated by Django 5.0.14 on 2026-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_school_email_alerts_enabled_school_email_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='credit_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('Credit', 'Credit balance')], default='Cash', max_length=20),
        ),
    ]
