# Generated by Django 5.0.14 on 2026-07-20 10:53

import core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_student_credit_balance_alter_feepayment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='pay_easypaisa_hash',
            field=core.crypto.EncryptedCharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='school',
            name='pay_jazzcash_password',
            field=core.crypto.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='pay_jazzcash_salt',
            field=core.crypto.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='sms_twilio_token',
            field=core.crypto.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='whatsapp_token',
            field=core.crypto.EncryptedCharField(blank=True, max_length=512),
        ),
    ]
