# Generated by Django 5.0.14 on 2026-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_encrypt_secrets_hash_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='pay_raast_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_raast_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_raast_instructions',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='school',
            name='pay_raast_qr',
            field=models.FileField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa'), ('RAAST', 'RAAST QR'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('Credit', 'Credit balance')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='onlinepayment',
            name='gateway',
            field=models.CharField(choices=[('bank', 'Bank transfer'), ('raast', 'RAAST QR'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=20),
        ),
    ]
