# Generated by Django 5.0.14 on 2026-07-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_school_pay_raast_enabled_school_pay_raast_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('Leaving', 'Leaving Certificate'), ('Character', 'Character Certificate'), ('Bonafide', 'Bonafide Certificate'), ('Birth', 'Date of Birth Certificate'), ('Fee', 'Fee Certificate')], default='Leaving', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.paymentsource'),
        ),
    ]
