# Generated by Django 5.0.14 on 2026-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='app_apk',
            field=models.FileField(blank=True, null=True, upload_to='school/apk/'),
        ),
    ]
