# Generated by Django 5.0.14 on 2026-07-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_school_app_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='app_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
