# Generated by Django 5.0.14 on 2026-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_school_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='established',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='hidden_nav',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='login_headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='school',
            name='login_tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='receipt_footer',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
