# Generated by Django 5.0.14 on 2026-07-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_school_address_school_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='core.profile'),
        ),
        migrations.AddField(
            model_name='school',
            name='tt_break_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='tt_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=40),
        ),
        migrations.AddField(
            model_name='school',
            name='tt_periods_per_day',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='periods_per_week',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
