# Generated by Django 5.0.14 on 2026-07-21 11:59

from django.db import migrations, models


def add_saturday(apps, schema_editor):
    """Existing schools still on the old Mon-Fri default now include Saturday
    (6-day week is the norm here). Schools that customised their days are left
    untouched."""
    School = apps.get_model('core', 'School')
    School.objects.filter(tt_days='Mon,Tue,Wed,Thu,Fri').update(
        tt_days='Mon,Tue,Wed,Thu,Fri,Sat')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_classroom_class_teacher_school_tt_break_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tt_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat', max_length=40),
        ),
        migrations.RunPython(add_saturday, migrations.RunPython.noop),
    ]
