from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('attendance/', views.attendance_mark, name='attendance_mark'),
    path('attendance/register/', views.attendance_register, name='attendance_register'),
    path('marks/', views.marks_entry, name='marks_entry'),
    path('my-attendance/', views.my_attendance, name='my_attendance'),
    path('my-results/', views.my_results, name='my_results'),
    path('report-card/<int:pk>/<int:exam_pk>/', views.report_card, name='report_card'),
    path('report-cards/', views.report_cards_bulk, name='report_cards_bulk'),
    path('my-subjects/', views.my_subjects, name='my_subjects'),
    path('my-timetable/', views.my_timetable, name='my_timetable'),
    path('my-datesheet/', views.my_datesheet, name='my_datesheet'),
    path('my-profile/', views.my_profile, name='my_profile'),
    path('student-photo/<int:pk>/', views.student_photo, name='student_photo'),
    path('school-logo/', views.school_logo, name='school_logo'),
    path('profile-photo/<int:pk>/', views.profile_photo, name='profile_photo'),
    path('account/', views.account, name='account'),
    path('material/<int:pk>/download/', views.material_download, name='material_download'),
    path('my-assignments/', views.my_assignments, name='my_assignments'),
    path('my-quizzes/', views.my_quizzes, name='my_quizzes'),
    path('teacher/assignments/', views.teacher_assignments, name='teacher_assignments'),
    path('teacher/quizzes/', views.teacher_quizzes, name='teacher_quizzes'),
    path('teacher/timetable/', views.teacher_timetable, name='teacher_timetable'),
    path('teacher/my-hr/', views.my_hr, name='my_hr'),
    path('assignment/<int:pk>/file/', views.assignment_file, name='assignment_file'),
    path('submission/<int:pk>/file/', views.submission_file, name='submission_file'),
    path('assignment/<int:pk>/submissions-zip/', views.assignment_submissions_zip, name='assignment_submissions_zip'),
    path('fees/collection/', views.fee_collection, name='fee_collection'),
    path('fees/student/<int:pk>/', views.student_fees, name='student_fees'),
    path('fees/receipt/<int:pk>/', views.receipt_view, name='receipt_view'),
    path('fees/challans/print/', views.challans_bulk, name='challans_bulk'),
    path('fees/receipts/', views.receipts, name='receipts'),
    path('fees/defaulters/', views.defaulters, name='defaulters'),
    path('fees/expenses/', views.expenses, name='expenses'),
    path('owner/students/', views.owner_students, name='owner_students'),
    path('owner/staff/', views.owner_staff, name='owner_staff'),
    path('owner/finance/', views.owner_finance, name='owner_finance'),
    path('principal/academics/', views.principal_academics, name='principal_academics'),
    path('principal/staff/', views.principal_staff, name='principal_staff'),
    path('principal/approvals/', views.principal_approvals, name='principal_approvals'),
    path('my-fees/', views.my_fees, name='my_fees'),
    path('my-fees/voucher/<int:pk>/', views.my_fee_voucher, name='my_fee_voucher'),
    path('my-fees/pay/<int:pk>/', views.pay_online, name='pay_online'),
    path('pay/callback/<str:gateway>/', views.payment_callback, name='payment_callback'),
    path('fees/online/', views.online_payments, name='online_payments'),
    path('fees/online/proof/<int:pk>/', views.payment_proof, name='payment_proof'),
    path('admissions/', views.admissions, name='admissions'),
    path('admissions/convert/<int:pk>/', views.applicant_convert, name='applicant_convert'),
    path('communication/', views.communication, name='communication'),
    path('transport/', views.transport, name='transport'),
    path('library/', views.library, name='library'),
    path('hostel/', views.hostel, name='hostel'),
    path('discipline/', views.discipline, name='discipline'),
    path('students/', views.students_list, name='students_list'),
    path('students/add/', views.student_add, name='student_add'),
    path('students/import/', views.students_import, name='students_import'),
    path('students/<int:pk>/', views.student_detail, name='student_detail'),
    path('students/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('classes/', views.classes_manage, name='classes_manage'),
    path('timetable/manage/', views.timetable_manage, name='timetable_manage'),
    path('settings/', views.school_settings, name='school_settings'),
    path('settings/backup/', views.backup_download, name='backup_download'),
    path('settings/restore/', views.restore_db, name='restore_db'),
    path('staff/', views.staff_list, name='staff_list'),
    path('staff/import/', views.staff_import, name='staff_import'),
    path('staff/attendance/', views.staff_attendance, name='staff_attendance'),
    path('staff/payroll/', views.payroll, name='payroll'),
    path('staff/payslip/<int:pk>/', views.payslip_pdf, name='payslip_pdf'),
    path('staff/leave/', views.staff_leave, name='staff_leave'),
    path('exams/datesheet/', views.exam_datesheet, name='exam_datesheet'),
    path('exams/rooms/', views.exam_rooms, name='exam_rooms'),
    path('exams/seating/', views.exam_seating, name='exam_seating'),
    path('promotion/', views.promotion, name='promotion'),
    path('certificates/', views.certificates, name='certificates'),
    path('id-cards/', views.id_cards, name='id_cards'),
    path('reports/', views.reports, name='reports'),
    path('certificates/view/<int:pk>/', views.certificate_view, name='certificate_view'),
    path('calendar/', views.calendar, name='calendar'),
    path('inventory/', views.inventory, name='inventory'),
    path('visitors/', views.visitors, name='visitors'),
    path('users/', views.users_list, name='users_list'),
    path('audit/', views.audit_log, name='audit_log'),
    path('coming-soon/', views.coming_soon, name='coming_soon'),
    path('help/', views.help_guide, name='help_guide'),
    path('login/', views.LockoutLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout-get/', views.logout_then_login, name='logout_get'),
    path('account/password/', views.ForcedPasswordChangeView.as_view(),
         name='password_change'),
    path('account/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),
    
    # SaaS admin routes
    path('saas-admin/', views.saas_admin_dashboard, name='saas_admin_dashboard'),
    path('saas-admin/school/add/', views.saas_school_add, name='saas_school_add'),
    path('saas-admin/school/<int:pk>/edit/', views.saas_school_edit, name='saas_school_edit'),
    path('saas-admin/school/<int:pk>/toggle/', views.saas_school_toggle, name='saas_school_toggle'),
    path('saas-admin/school/<int:pk>/delete/', views.saas_school_delete, name='saas_school_delete'),
    path('subscription-expired/', views.subscription_expired, name='subscription_expired'),
]